blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/xenolphthalein/order-history-exporter-for-amazon/discussions
    about: Please use Discussions for questions, troubleshooting, and general help.
